
=head1 JavaScript backend for Rakudo [Project Title Here]

=over 1

=item Name:

Paweł Murias

=item Amount Requested:

USD 1,234 [How much is your project worth?]

=back

=head2 Synopsis

[A short description]

JavaScript backend for rakudo.

=head2 Benefits to the Perl Community

[Is this work worth doing? Why should the Perl Community grant
this project?]

=head2 Deliverables

[Quantifiable results e.g. "Improve X modules in ways Y and Z",
"Write 3 articles for X website".]

[If you cannot clearly define the deliverables, you are not quite ready
to submit this.]

Upload rakudo-js to npm and CPAN.
Have this rakudo-js be able compile our choosen subset roast to JavaScript and pass them in a modern browser.
Write a simple REPL in Perl 6 that will run in a modern browser.

=head2 Project Details

[A more detailed description.]

[It will be beneficial to include the progress made to date (if any).
If you aren't the primary maintainer of the project you want funding
for, show that you have endorsement from the primary maintainer.]

=head2 Inch-stones

[Break down your project into small chunks. By listing your tasks
adequately, other people will understand you know what you need to do.]

[Try and think in "inch-stones" rather than "mile-stones". Breaking down
your grant into many small goals makes it harder to overlook
difficulties, and easier to see progress as you complete your grant.]

* cleanup the array handling in nqp-js 
* go through the moarvm opcode list and where it's possible write tests for untested opcode and implemement them in nqp-js
* do the obvious speedups for the code generated by nqp-js
* get the part of the rakudo setting written in NQP (mostly the metamodel and code bootstraping it) to compile under nqp-js
* implement a bunch p6 specific ops
* get rakudo to compile on nqp-js
* get rakudo compiled to js to correctly compile nqp::say("Hello World")
* get the rakudo setting to compile
* get rakudo compiled to js to correctly compile say("Hello World")
* get Test.pm to correctly compile
* pass a first test
* go through roast test fixing bugs and implementing missing things to make them pass
* pass the part of roast we focus on node.js
* be able to webpack the generated javascript code
* be able to run tests in the browser
* pass the part of roast we focus on in a browser
* polish up source maps
* implement (and test) interop with javascript code
* upload rakudo-js on npm
* write a simple Perl6 REPL that should run in modern browser
* put the REPL on try.perl6.org

=head2 Project Schedule

[How long will the project take? When can you begin work?
Be realistic.]

=head2 Completeness Criteria

[Describe how your grant can be evaluated. For instance, code will be
merged in Perl tree, or a module will be released to CPAN with the
specified features, etc.]

rakudo-js released on npm
a simple REPL running in Chrome

=head2 Bio

Worked on mildew/smop.
[Who are you? What makes you the best person to work on this project?]

[Before submitting this proposal, review it again. Check the POD syntax.
Use a spell checker.  If possible, get it reviewed by someone who
understands the value of your project.]

=cut


